############################################
# TimetableSpawner main configuration file #
############################################

#ticks needed to destroy inactive trains. Set it to 0 to turn this feature off.
destroy-trains: 0
#don't destroy trains with this tag:
dont-destroy-tag: dontdestroy

seconds-to-display-on-board: 20

departure-boards:
  test1|3:
    - R1|30 0/5 * * * *|City Hall|3|_
    - R2|0/10 * * * *
  test2|3:
    - R1|56 1/5 * * * *